-- Weekly marketing performance seed data (Jun 8 - Jun 28, 2026)
-- Monday-start weeks. Blank values are NULL. Numbers stored without commas.
-- Safe to re-run: upserts on id.

insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_facebook_nobody_move', '2026-06-08', 'Nobody Move', 'Facebook', 'Nobody Move Facebook', 159, 2, 1145, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_facebook_relocators', '2026-06-08', 'Relocators', 'Facebook', 'Relocators Facebook', 2965, -2, 289, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_facebook_sisters_in_charge', '2026-06-08', 'Sisters in Charge', 'Facebook', 'Sisters in Charge Facebook', 2810, 1, 101, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_facebook_robert_personal', '2026-06-08', 'Robert Personal', 'Facebook', 'Robert Personal Facebook', 5190, -1, 4403, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_instagram_robert_personal', '2026-06-08', 'Robert Personal', 'Instagram', 'Robert Personal Instagram', null, null, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_instagram_nobody_move', '2026-06-08', 'Nobody Move', 'Instagram', 'Nobody Move Instagram', 804, 1, 2210, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_instagram_relocators', '2026-06-08', 'Relocators', 'Instagram', 'Relocators Instagram', 2974, -3, 169, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_instagram_sisters_in_charge', '2026-06-08', 'Sisters in Charge', 'Instagram', 'Sisters in Charge Instagram', 1630, -1, 169, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_linkedin_robert_personal', '2026-06-08', 'Robert Personal', 'LinkedIn', 'Robert Personal LinkedIn', 3922, 3, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_tiktok_nobody_move', '2026-06-08', 'Nobody Move', 'TikTok', 'Nobody Move TikTok', 5501, 0, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_tiktok_relocators', '2026-06-08', 'Relocators', 'TikTok', 'Relocators TikTok', 455, 0, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-08_youtube_relocators', '2026-06-08', 'Relocators', 'YouTube', 'Relocators YouTube', 2896, 1, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_facebook_nobody_move', '2026-06-15', 'Nobody Move', 'Facebook', 'Nobody Move Facebook', 161, 2, 196, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_facebook_relocators', '2026-06-15', 'Relocators', 'Facebook', 'Relocators Facebook', 2968, 3, 1245, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_facebook_sisters_in_charge', '2026-06-15', 'Sisters in Charge', 'Facebook', 'Sisters in Charge Facebook', 2810, 0, 783, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_facebook_robert_personal', '2026-06-15', 'Robert Personal', 'Facebook', 'Robert Personal Facebook', 5187, -3, 6677, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_instagram_robert_personal', '2026-06-15', 'Robert Personal', 'Instagram', 'Robert Personal Instagram', 9906, -9, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_instagram_nobody_move', '2026-06-15', 'Nobody Move', 'Instagram', 'Nobody Move Instagram', 805, 1, 1290, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_instagram_relocators', '2026-06-15', 'Relocators', 'Instagram', 'Relocators Instagram', 2973, -1, 700, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_instagram_sisters_in_charge', '2026-06-15', 'Sisters in Charge', 'Instagram', 'Sisters in Charge Instagram', 1630, 0, 421, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_linkedin_robert_personal', '2026-06-15', 'Robert Personal', 'LinkedIn', 'Robert Personal LinkedIn', 3927, 5, 423, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_tiktok_nobody_move', '2026-06-15', 'Nobody Move', 'TikTok', 'Nobody Move TikTok', 5503, 2, 461, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_tiktok_relocators', '2026-06-15', 'Relocators', 'TikTok', 'Relocators TikTok', 456, 1, 248, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-15_youtube_relocators', '2026-06-15', 'Relocators', 'YouTube', 'Relocators YouTube', 2896, 0, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_facebook_nobody_move', '2026-06-22', 'Nobody Move', 'Facebook', 'Nobody Move Facebook', 162, 1, 355, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_facebook_relocators', '2026-06-22', 'Relocators', 'Facebook', 'Relocators Facebook', 2963, -5, 892, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_facebook_sisters_in_charge', '2026-06-22', 'Sisters in Charge', 'Facebook', 'Sisters in Charge Facebook', 2813, 3, 324, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_facebook_robert_personal', '2026-06-22', 'Robert Personal', 'Facebook', 'Robert Personal Facebook', 5183, -4, 2670, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_instagram_robert_personal', '2026-06-22', 'Robert Personal', 'Instagram', 'Robert Personal Instagram', 9874, -32, 774, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_instagram_nobody_move', '2026-06-22', 'Nobody Move', 'Instagram', 'Nobody Move Instagram', 804, -1, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_instagram_relocators', '2026-06-22', 'Relocators', 'Instagram', 'Relocators Instagram', 2965, -8, 633, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_instagram_sisters_in_charge', '2026-06-22', 'Sisters in Charge', 'Instagram', 'Sisters in Charge Instagram', 1627, -3, 292, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_linkedin_robert_personal', '2026-06-22', 'Robert Personal', 'LinkedIn', 'Robert Personal LinkedIn', 3941, 14, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_tiktok_nobody_move', '2026-06-22', 'Nobody Move', 'TikTok', 'Nobody Move TikTok', 5507, 4, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_tiktok_relocators', '2026-06-22', 'Relocators', 'TikTok', 'Relocators TikTok', 456, 0, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
insert into public.marketing_entries (id, entry_date, brand, platform, account_name, followers, new_followers, views, source) values ('wk_2026-06-22_youtube_relocators', '2026-06-22', 'Relocators', 'YouTube', 'Relocators YouTube', 2894, -2, null, 'Manual')
on conflict (id) do update set entry_date=excluded.entry_date, brand=excluded.brand, platform=excluded.platform, account_name=excluded.account_name, followers=excluded.followers, new_followers=excluded.new_followers, views=excluded.views, source='Manual', updated_at=now();
