-- Marketing Content Calendar seed — 4-week plan, Aug 24 to Sep 20, 2026.
-- Source: Relocators_NobodyMove_SistersInCharge_Calendar.xlsx (the three
-- '4-Week Calendar' tabs). 60 posts: 20 per brand.
--
-- Run AFTER marketing-content.sql, in Supabase -> SQL Editor. Safe to re-run:
-- every row upserts on id, so a second run refreshes the plan instead of
-- duplicating it. Status/Views/Reach stay for the team to fill in after posting.
--
-- Same content goes to Facebook and Instagram at the same time, so each post is
-- ONE row with platform 'Facebook + Instagram' (not two rows per post).

insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-24_relocators', '2026-08-24', 'Relocators', 'Facebook + Instagram', 'Mattress and box spring: how to bag, tape and carry without folding the frame', 'Reel', null, 'Scheduled', 'Theme: Packing & moving tips · Monday 11:00 AM ET · Target length: 30-45 sec · Source: Crosspost from IG', '2026-08-24', '11:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-25_relocators', '2026-08-25', 'Relocators', 'Facebook + Instagram', 'The first hire - what changed when it stopped being a one-truck operation', 'Reel', null, 'Scheduled', 'Theme: Founder story · Tuesday 5:00 PM ET · Target length: 45-60 sec · Source: Native upload', '2026-08-25', '17:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-27_relocators', '2026-08-27', 'Relocators', 'Facebook + Instagram', 'Room-by-room box labeling system - single graphic, no carousel', 'Static Post', null, 'Scheduled', 'Theme: Packing & moving tips (graphic) · Thursday 12:00 PM ET · Target length: n/a · Source: Native upload', '2026-08-27', '12:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-29_relocators', '2026-08-29', 'Relocators', 'Facebook + Instagram', 'Full job walkthrough: arrival, wrap, load-out, final sweep', 'Reel', null, 'Scheduled', 'Theme: Crew / behind the scenes · Saturday 3:00 AM ET · Target length: 40-50 sec · Source: Crosspost from IG', '2026-08-29', '03:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-30_relocators', '2026-08-30', 'Relocators', 'Facebook + Instagram', '6 AM dispatch - Dyana assigning trucks, crew loading pads and dollies', 'Reel', null, 'Scheduled', 'Theme: Crew / behind the scenes · Sunday 3:00 AM ET · Target length: 30-45 sec · Source: Crosspost from IG', '2026-08-30', '03:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-31_relocators', '2026-08-31', 'Relocators', 'Facebook + Instagram', 'Floor and door-jamb protection - what we lay down before a single box moves', 'Reel', null, 'Scheduled', 'Theme: Packing & moving tips · Monday 11:00 AM ET · Target length: 30-45 sec · Source: Crosspost from IG', '2026-08-31', '11:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-01_relocators', '2026-09-01', 'Relocators', 'Facebook + Instagram', 'Estate cleanout start-to-finish: what a full-house clear actually looks like', 'Reel', null, 'Scheduled', 'Theme: Service promo · Tuesday 5:00 PM ET · Target length: 45-60 sec · Source: Native upload', '2026-09-01', '17:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-03_relocators', '2026-09-03', 'Relocators', 'Facebook + Instagram', 'Long Island service map - towns covered, one clean graphic', 'Static Post', null, 'Scheduled', 'Theme: Service promo (graphic) · Thursday 12:00 PM ET · Target length: n/a · Source: Native upload', '2026-09-03', '12:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-05_relocators', '2026-09-05', 'Relocators', 'Facebook + Instagram', 'Labor Day weekend job - crew working while everyone else is off', 'Reel', null, 'Scheduled', 'Theme: Crew / behind the scenes · Saturday 3:00 AM ET · Target length: 40-50 sec · Source: Crosspost from IG', '2026-09-05', '03:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-06_relocators', '2026-09-06', 'Relocators', 'Facebook + Instagram', 'Why we''re bigger than moving, part 2 - the gap between the sale and the settle-in', 'Reel', null, 'Scheduled', 'Theme: Founder story · Sunday 3:00 AM ET · Target length: 45-60 sec · Source: Native upload', '2026-09-06', '03:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-07_relocators', '2026-09-07', 'Relocators', 'Facebook + Instagram', 'Heavy and fragile: marble, glass tops, stone - edge protection and weight support', 'Reel', null, 'Scheduled', 'Theme: Packing & moving tips · Monday 11:00 AM ET · Target length: 30-45 sec · Source: Crosspost from IG', '2026-09-07', '11:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-08_relocators', '2026-09-08', 'Relocators', 'Facebook + Instagram', 'A job that went wrong and the process change that came out of it', 'Reel', null, 'Scheduled', 'Theme: Founder story · Tuesday 5:00 PM ET · Target length: 45-60 sec · Source: Native upload', '2026-09-08', '17:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-10_relocators', '2026-09-10', 'Relocators', 'Facebook + Instagram', 'Client quote laid over an actual job photo from that move - not a screenshot', 'Static Post', null, 'Scheduled', 'Theme: Review (1 of 2 this month) · Thursday 12:00 PM ET · Target length: n/a · Source: Native upload', '2026-09-10', '12:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-12_relocators', '2026-09-12', 'Relocators', 'Facebook + Instagram', 'Commercial or institutional job - library, office, or facility move', 'Reel', null, 'Scheduled', 'Theme: Crew / behind the scenes · Saturday 3:00 AM ET · Target length: 40-50 sec · Source: Crosspost from IG', '2026-09-12', '03:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-13_relocators', '2026-09-13', 'Relocators', 'Facebook + Instagram', 'Walkthrough with a realtor or remodeler - where the handoff happens', 'Reel', null, 'Scheduled', 'Theme: Partner / collaboration · Sunday 3:00 AM ET · Target length: 45-60 sec · Source: Native upload', '2026-09-13', '03:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-14_relocators', '2026-09-14', 'Relocators', 'Facebook + Instagram', 'What NOT to pack yourself - the five items that cost people money', 'Reel', null, 'Scheduled', 'Theme: Packing & moving tips · Monday 11:00 AM ET · Target length: 30-45 sec · Source: Crosspost from IG', '2026-09-14', '11:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-15_relocators', '2026-09-15', 'Relocators', 'Facebook + Instagram', 'Estate sale to auction pipeline - what happens to what doesn''t move', 'Reel', null, 'Scheduled', 'Theme: Service promo · Tuesday 5:00 PM ET · Target length: 45-60 sec · Source: Native upload', '2026-09-15', '17:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-17_relocators', '2026-09-17', 'Relocators', 'Facebook + Instagram', 'Moving-week countdown checklist - 7 days out to day-of', 'Static Post', null, 'Scheduled', 'Theme: Packing & moving tips (graphic) · Thursday 12:00 PM ET · Target length: n/a · Source: Native upload', '2026-09-17', '12:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-19_relocators', '2026-09-19', 'Relocators', 'Facebook + Instagram', 'Training day footage - how the standard gets set (your best post format to date)', 'Reel', null, 'Scheduled', 'Theme: Crew / behind the scenes · Saturday 3:00 AM ET · Target length: 40-50 sec · Source: Crosspost from IG', '2026-09-19', '03:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-20_relocators', '2026-09-20', 'Relocators', 'Facebook + Instagram', 'Crew footage from the job, client''s words as voiceover - the testimonial fix', 'Reel', null, 'Scheduled', 'Theme: Review (2 of 2 this month) · Sunday 3:00 AM ET · Target length: 40-50 sec · Source: Crosspost from IG', '2026-09-20', '03:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-24_nobody_move', '2026-08-24', 'Nobody Move', 'Facebook + Instagram', 'Why Nobody Move exists - the gap nobody owns between closing and settled', 'Reel', null, 'Scheduled', 'Theme: Brand / founder POV · Monday 4:30 PM ET · Target length: 90-120 sec · Source: Post to FB + IG', '2026-08-24', '16:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-25_nobody_move', '2026-08-25', 'Nobody Move', 'Facebook + Instagram', 'First day of school - the walk-in moment, filmed the week it''s happening', 'Reel', null, 'Scheduled', 'Theme: Elle Jae / school & kids · Tuesday 2:00 PM ET · Target length: 40-60 sec · Source: Post to FB + IG', '2026-08-25', '14:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-26_nobody_move', '2026-08-26', 'Nobody Move', 'Facebook + Instagram', 'Hack #5: photograph every wall and floor before the truck arrives', 'Reel', null, 'Scheduled', 'Theme: Moving hacks (numbered series) · Wednesday 4:00 PM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-08-26', '16:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-27_nobody_move', '2026-08-27', 'Nobody Move', 'Facebook + Instagram', 'Who owns the client after the deal closes? - direct sequel to ''Industry Changing''', 'Reel', null, 'Scheduled', 'Theme: The Standard / industry · Thursday 1:00 PM ET · Target length: 90 sec · Source: Post to FB + IG', '2026-08-27', '13:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-29_nobody_move', '2026-08-29', 'Nobody Move', 'Facebook + Instagram', 'Packing confidence, not just supplies - activity book walkthrough', 'Reel', null, 'Scheduled', 'Theme: Elle Jae / school & kids · Saturday 3:00 PM ET · Target length: 40-60 sec · Source: Post to FB + IG', '2026-08-29', '15:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-31_nobody_move', '2026-08-31', 'Nobody Move', 'Facebook + Instagram', 'Timeline vs. deadline - the realization that changed how I run transitions', 'Reel', null, 'Scheduled', 'Theme: Brand / founder POV · Monday 4:30 PM ET · Target length: 90-120 sec · Source: Post to FB + IG', '2026-08-31', '16:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-01_nobody_move', '2026-09-01', 'Nobody Move', 'Facebook + Instagram', 'New district, new kid - first week check-in with Elle Jae', 'Reel', null, 'Scheduled', 'Theme: Elle Jae / school & kids · Tuesday 2:00 PM ET · Target length: 40-60 sec · Source: Post to FB + IG', '2026-09-01', '14:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-02_nobody_move', '2026-09-02', 'Nobody Move', 'Facebook + Instagram', 'Hack #6: get the estimate as a range, not a single number', 'Reel', null, 'Scheduled', 'Theme: Moving hacks (numbered series) · Wednesday 4:00 PM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-02', '16:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-03_nobody_move', '2026-09-03', 'Nobody Move', 'Facebook + Instagram', 'What a Transitional Coordinator actually does, minute by minute', 'Reel', null, 'Scheduled', 'Theme: The Standard / industry · Thursday 1:00 PM ET · Target length: 90-120 sec · Source: Post to FB + IG', '2026-09-03', '13:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-05_nobody_move', '2026-09-05', 'Nobody Move', 'Facebook + Instagram', 'Miles & Scoot - the locker combination episode', 'Reel', null, 'Scheduled', 'Theme: Elle Jae / school & kids · Saturday 3:00 PM ET · Target length: 40-60 sec · Source: Post to FB + IG', '2026-09-05', '15:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-07_nobody_move', '2026-09-07', 'Nobody Move', 'Facebook + Instagram', 'What I learned taking this standard to the industry - the pushback and what it proved', 'Reel', null, 'Scheduled', 'Theme: Brand / founder POV · Monday 4:30 PM ET · Target length: 90-120 sec · Source: Post to FB + IG', '2026-09-07', '16:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-08_nobody_move', '2026-09-08', 'Nobody Move', 'Facebook + Instagram', 'Kids answer: what were you most worried about? - unscripted, their words', 'Reel', null, 'Scheduled', 'Theme: Elle Jae / school & kids · Tuesday 2:00 PM ET · Target length: 40-60 sec · Source: Post to FB + IG', '2026-09-08', '14:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-09_nobody_move', '2026-09-09', 'Nobody Move', 'Facebook + Instagram', 'Hack #7: inventory what is NOT moving, not just what is', 'Reel', null, 'Scheduled', 'Theme: Moving hacks (numbered series) · Wednesday 4:00 PM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-09', '16:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-10_nobody_move', '2026-09-10', 'Nobody Move', 'Facebook + Instagram', 'CAP certification - what agents are actually trained on and why it''s not the deal', 'Reel', null, 'Scheduled', 'Theme: The Standard / industry · Thursday 1:00 PM ET · Target length: 90-120 sec · Source: Post to FB + IG', '2026-09-10', '13:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-12_nobody_move', '2026-09-12', 'Nobody Move', 'Facebook + Instagram', 'PTA partnership - bringing the books into schools, footage from a school visit', 'Reel', null, 'Scheduled', 'Theme: Elle Jae / school & kids · Saturday 3:00 PM ET · Target length: 40-60 sec · Source: Post to FB + IG', '2026-09-12', '15:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-14_nobody_move', '2026-09-14', 'Nobody Move', 'Facebook + Instagram', 'From a $4,000 box truck to a standard - the through-line', 'Reel', null, 'Scheduled', 'Theme: Brand / founder POV · Monday 4:30 PM ET · Target length: 90-120 sec · Source: Post to FB + IG', '2026-09-14', '16:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-15_nobody_move', '2026-09-15', 'Nobody Move', 'Facebook + Instagram', 'Six weeks in - how the new kid is doing now, follow-up to the Aug 25 post', 'Reel', null, 'Scheduled', 'Theme: Elle Jae / school & kids · Tuesday 2:00 PM ET · Target length: 40-60 sec · Source: Post to FB + IG', '2026-09-15', '14:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-16_nobody_move', '2026-09-16', 'Nobody Move', 'Facebook + Instagram', 'Hack #8: the three tasks to finish before a single box comes inside', 'Reel', null, 'Scheduled', 'Theme: Moving hacks (numbered series) · Wednesday 4:00 PM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-16', '16:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-17_nobody_move', '2026-09-17', 'Nobody Move', 'Facebook + Instagram', 'The post-close gap, mapped: what happens at 30, 60 and 90 days', 'Reel', null, 'Scheduled', 'Theme: The Standard / industry · Thursday 1:00 PM ET · Target length: 90-120 sec · Source: Post to FB + IG', '2026-09-17', '13:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-19_nobody_move', '2026-09-19', 'Nobody Move', 'Facebook + Instagram', 'Military family moves - the mid-year school change nobody plans for', 'Reel', null, 'Scheduled', 'Theme: Elle Jae / school & kids · Saturday 3:00 PM ET · Target length: 40-60 sec · Source: Post to FB + IG', '2026-09-19', '15:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-24_sisters_in_charge', '2026-08-24', 'Sisters in Charge', 'Facebook + Instagram', 'The five places people forget to check: drawers, cushions, cabinets, closets, attics', 'Reel', null, 'Scheduled', 'Theme: Cleanout / what-to-keep education · Monday 6:00 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-08-24', '06:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-25_sisters_in_charge', '2026-08-25', 'Sisters in Charge', 'Facebook + Instagram', 'Garage sale vs. estate sale vs. auction - which one your situation actually calls for', 'Reel', null, 'Scheduled', 'Theme: Estate sale how-it-works · Tuesday 1:00 PM ET · Target length: 25-30 sec · Source: Post to FB + IG', '2026-08-25', '13:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-27_sisters_in_charge', '2026-08-27', 'Sisters in Charge', 'Facebook + Instagram', 'Why the market sets the price, not the memory - walking a real appraisal', 'Reel', null, 'Scheduled', 'Theme: Valuation & pricing education · Thursday 6:30 AM ET · Target length: 25-35 sec · Source: Post to FB + IG', '2026-08-27', '06:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-28_sisters_in_charge', '2026-08-28', 'Sisters in Charge', 'Facebook + Instagram', 'Walkthrough of this weekend''s sale - what is on the floor and what to come early for', 'Reel', null, 'Scheduled', 'Theme: Upcoming sale preview · Friday 7:30 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-08-28', '07:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-29_sisters_in_charge', '2026-08-29', 'Sisters in Charge', 'Facebook + Instagram', 'Doors open - the first twenty minutes of a live sale', 'Reel', null, 'Scheduled', 'Theme: Sale day / live footage · Saturday 8:00 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-08-29', '08:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-08-31_sisters_in_charge', '2026-08-31', 'Sisters in Charge', 'Facebook + Instagram', 'Pause on what cannot be replaced: photos, letters, records, jewelry boxes', 'Reel', null, 'Scheduled', 'Theme: Cleanout / what-to-keep education · Monday 6:00 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-08-31', '06:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-01_sisters_in_charge', '2026-09-01', 'Sisters in Charge', 'Facebook + Instagram', 'What actually happens in the two weeks before a sale opens', 'Reel', null, 'Scheduled', 'Theme: Estate sale how-it-works · Tuesday 1:00 PM ET · Target length: 25-30 sec · Source: Post to FB + IG', '2026-09-01', '13:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-03_sisters_in_charge', '2026-09-03', 'Sisters in Charge', 'Facebook + Instagram', 'Three things that move a price: demand, condition, provenance', 'Reel', null, 'Scheduled', 'Theme: Valuation & pricing education · Thursday 6:30 AM ET · Target length: 25-35 sec · Source: Post to FB + IG', '2026-09-03', '06:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-04_sisters_in_charge', '2026-09-04', 'Sisters in Charge', 'Facebook + Instagram', 'This weekend''s lots - the three pieces worth showing up early for', 'Reel', null, 'Scheduled', 'Theme: Upcoming sale preview · Friday 7:30 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-04', '07:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-05_sisters_in_charge', '2026-09-05', 'Sisters in Charge', 'Facebook + Instagram', 'Early birds - why the first hour of a sale is different from the last', 'Reel', null, 'Scheduled', 'Theme: Sale day / live footage · Saturday 8:00 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-05', '08:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-07_sisters_in_charge', '2026-09-07', 'Sisters in Charge', 'Facebook + Instagram', 'Do not rush the cleanout - what one extra week of patience is worth', 'Reel', null, 'Scheduled', 'Theme: Cleanout / what-to-keep education · Monday 6:00 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-07', '06:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-08_sisters_in_charge', '2026-09-08', 'Sisters in Charge', 'Facebook + Instagram', 'Who does what: Kathy, Joy and the team on sale day', 'Reel', null, 'Scheduled', 'Theme: Estate sale how-it-works · Tuesday 1:00 PM ET · Target length: 25-30 sec · Source: Post to FB + IG', '2026-09-08', '13:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-10_sisters_in_charge', '2026-09-10', 'Sisters in Charge', 'Facebook + Instagram', 'Before you sell something vintage, check these three markings', 'Reel', null, 'Scheduled', 'Theme: Valuation & pricing education · Thursday 6:30 AM ET · Target length: 25-35 sec · Source: Post to FB + IG', '2026-09-10', '06:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-11_sisters_in_charge', '2026-09-11', 'Sisters in Charge', 'Facebook + Instagram', 'Behind the doors - setup day at this weekend''s sale', 'Reel', null, 'Scheduled', 'Theme: Upcoming sale preview · Friday 7:30 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-11', '07:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-12_sisters_in_charge', '2026-09-12', 'Sisters in Charge', 'Facebook + Instagram', 'Live from the sale - walkthrough as the first buyers come through', 'Reel', null, 'Scheduled', 'Theme: Sale day / live footage · Saturday 8:00 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-12', '08:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-14_sisters_in_charge', '2026-09-14', 'Sisters in Charge', 'Facebook + Instagram', 'How helping Nana clear her house became a business - the full version', 'Reel', null, 'Scheduled', 'Theme: Founder / origin story · Monday 6:00 AM ET · Target length: 30-35 sec · Source: Post to FB + IG', '2026-09-14', '06:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-15_sisters_in_charge', '2026-09-15', 'Sisters in Charge', 'Facebook + Instagram', 'Estate sale vs. auction - when the auction actually makes the family more money', 'Reel', null, 'Scheduled', 'Theme: Estate sale how-it-works · Tuesday 1:00 PM ET · Target length: 25-30 sec · Source: Post to FB + IG', '2026-09-15', '13:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-17_sisters_in_charge', '2026-09-17', 'Sisters in Charge', 'Facebook + Instagram', 'The item everyone assumed was worthless - and what it sold for', 'Reel', null, 'Scheduled', 'Theme: Valuation & pricing education · Thursday 6:30 AM ET · Target length: 25-35 sec · Source: Post to FB + IG', '2026-09-17', '06:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-18_sisters_in_charge', '2026-09-18', 'Sisters in Charge', 'Facebook + Instagram', 'Final walkthrough before the doors open tomorrow', 'Reel', null, 'Scheduled', 'Theme: Upcoming sale preview · Friday 7:30 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-18', '07:30')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
insert into public.marketing_content (id, date, brand, platform, title, content_type, owner, status, notes, publish_date, publish_time) values ('mc_2026-09-19_sisters_in_charge', '2026-09-19', 'Sisters in Charge', 'Facebook + Instagram', 'Client''s words as voiceover over sale-day footage - not a screenshot', 'Reel', null, 'Scheduled', 'Theme: Review (as video) · Saturday 8:00 AM ET · Target length: 20-30 sec · Source: Post to FB + IG', '2026-09-19', '08:00')
on conflict (id) do update set date=excluded.date, brand=excluded.brand, platform=excluded.platform, title=excluded.title, content_type=excluded.content_type, owner=excluded.owner, status=excluded.status, notes=excluded.notes, publish_date=excluded.publish_date, publish_time=excluded.publish_time, updated_at=now();
